name: Rarity
main: xyz.acrylicstyle.rarity.Rarity
version: 0.0.1-SNAPSHOT
api-version: 1.8.8
author: acrylic-style
depend: [ProtocolLib]
commands:
  giveitem:
    usage: /<command>
  addenchant:
    usage: /<command>